### ISSUE TITLE
hello, does this work?

### ISSUE THREAD

**Issue by 9crk** [narendraj9/speaker-reco#1]
hello, does this work? how's it work?

**Comment by narendraj9** [comment]
It's been a long time since I wrote this. Here is what I remember: 

Human voice has characteristics that can be used to distinguish your voice from someone else's voice. You inject energy into bands of audible frequencies with a pattern that is somewhat unique to you. If we can somehow convert this distribution into vectors, we can use those vectors for identifying your voice and hence identifying you. 

The conversion from audio signals to feature vectors is done with MFCC's. You can read up on that. 

Once we have those vectors, we can use any Machine Learning technique that we see fit. In this particular project, we used Support Vector Machines for classifying your voice from the voice of the rest of the people that we train the model with. You can read more about SVM's. 

It's like we project your voice into an n-dimensional space and it so happens that your voice tends to lie in a corner that's unique to you.

Note: I might be wrong at some places. This is the gist of the whole thing we did here. This should give you a good departure point. Have a great time! :)

**Comment by 9crk** [comment]
it's nice of you to reply,thanks!

I'v just read a bunch of papers,and I tried to use fft to get feature vector like this:
for(i=0;i<sizeof(fft_result);i++){
    if(fft_result[i] > threshold)feature[i]++;
}
for every short voice.

I found it's hard to work out a usable one.
and I'm wondering was I going the wrong way...

**Comment by 9crk** [comment]
seems that use i-vector in kaldi is a solution.

**Comment by 9crk** [comment]
if you use a few(like one or two) voice to train your svm model, it might not be good in result.
so I'm finding a good way for less train data.

**Comment by narendraj9** [comment]
@9crk  Cool! :) Please share your findings here. Would love to learn about how you do it. :)
